### PR TITLE
Add support for specifying package name for assets

### PR DESCRIPTION
**Pull request by jmacpherson**
I've tested it out on an iPad (6th Gen) running iOS 13.6.1, and a OnePlus 5T running Android 10

### CODE REVIEW

**Comment by erickzanardo** [comment]
LGTM, would be nice to mention this new prop on the README though

**Comment by jmacpherson** [comment]
> LGTM, would be nice to mention this new prop on the README though

I've added reference to the `package` param in the example using assets.

**Comment by jmacpherson** [comment]
@erickzanardo Hi Erick, wondering if there's anything else that you'd like to see done for this PR.

**Comment by erickzanardo** [comment]
Hey @jmacpherson not really, the PR is fine, I am just overwhelmed lately and ended up forgetting to test, merge and release this. Sorry about that, thanks for the reminder, I am gonna try to do release this tonight!

**Review by erickzanardo — APPROVED** [review]

**Comment by erickzanardo** [comment]
Released on `0.0.3`

**Comment by jmacpherson** [comment]
> Hey @jmacpherson not really, the PR is fine, I am just overwhelmed lately and ended up forgetting to test, merge and release this. Sorry about that, thanks for the reminder, I am gonna try to do release this tonight!

No worries. Maintaining an open source project definitely takes time, on top of all the other things life throws at us. Thanks for taking the time!

**Pull request merged**
