### PR TITLE
feature: Add audio player listener feature

### PR DESCRIPTION
**Pull request by jmacpherson**
Also, updated readme to reflect upcoming changes in iOS delegation on the `twilio_programmable_video` side of things.

Opening this as a DRAFT, as the work it is being developed in concert with is not yet published. Will update this PR as it becomes relevant.

### CODE REVIEW

**Comment by erickzanardo** [comment]
Thanks for the contribution, I made a quick review and LGTM, will review again when the PR is not in draft anymore.

Also, is this something that can be added to iOS as well? I would like to avoid having features on one platform and not on the other if possible.

**Comment by jmacpherson** [comment]
Yeah, I can look at adding it on iOS as well. Do not personally need it, as using the iOS delegation, already get notified of play/stop requests, etc, but that doesn't mean it won't be useful to someone else.

**Comment by jmacpherson** [comment]
Added an implementation to iOS. In order to do this, had to refactor the `SinglePlayer` to use `AVPlayer` rather than `AVAudioPlayer`, as the former allows KVO on its `rate`, whereas the latter does not.

In this implementation, `rate` is used to determine whether the player is playing at this time. A rate of `0` indicates that it is not playing, while a rate >`0` indicates that it is.

**Comment by erickzanardo** [comment]
> Added an implementation to iOS. In order to do this, had to refactor the `SinglePlayer` to use `AVPlayer` rather than `AVAudioPlayer`, as the former allows KVO on its `rate`, whereas the latter does not.
> 
> In this implementation, `rate` is used to determine whether the player is playing at this time. A rate of `0` indicates that it is not playing, while a rate >`0` indicates that it is.

Hmm, that might pose a problem, I remember using intentionally using `AVAudioPlayer` due to it having a better perfomance than `AVPlayer`, so it worked better for games and things like that.

I will probably have to think a little bit on how we could make both things live together.

**Comment by jmacpherson** [comment]
The general solution to this problem of `AVAudioPlayer` not working properly with KVO that I have seen when researching this issue is usage of a periodic timer to check its status. Such an approach seemed inelegant at best, and inefficient/error prone at worst to me, which is why in this implementation, I opted for consistency with the implementation used by `LoopPlayer`. If there are performance issues observed with this implementation, I'd be happy to look at alternatives, though I will also note, that the native layer listener functionality added here is superfluous to my personal use case on iOS.

**Comment by dw2kim** [comment]
@erickzanardo @jmacpherson 
I don't have much experience with the `AVPlayer` and `AVAudioPlayer` but looks like `AVPlayer` is more suitable for the performance as well based on this:
https://stackoverflow.com/a/38081566

Also, with a quick glances, I see that [`AVPlayer`](https://developer.apple.com/documentation/avfoundation/avplayer) has more flexible than [`AVAudioPlayer`](https://developer.apple.com/documentation/avfaudio/avaudioengine) based on the Apple Docs.

**Review by dw2kim — APPROVED** [review]
The changes look good to me. Tested on iOS simulator and it worked well.

**Comment by erickzanardo** [comment]
> @erickzanardo @jmacpherson
> I don't have much experience with the `AVPlayer` and `AVAudioPlayer` but looks like `AVPlayer` is more suitable for the performance as well based on this:
> https://stackoverflow.com/a/38081566
> 
> Also, with a quick glances, I see that [`AVPlayer`](https://developer.apple.com/documentation/avfoundation/avplayer) has more flexible than [`AVAudioPlayer`](https://developer.apple.com/documentation/avfaudio/avaudioengine) based on the Apple Docs.

I am unsure, I remember making some good benchmarks and AVAudioPlayer performed way better.

But either way I am willing to give this a try, I will merge this and make a new release later today, then lets keep an eye on how well Ocarina is performing and we can keep or rollback in the future.

Once again, thanks for the contribution @jmacpherson

**Comment by erickzanardo** [comment]
Done, released on `0.1.2`!

**Comment by jmacpherson** [comment]
Thanks so much for being willing to give it a shot. If we do observe issues going forward, happy to look into alternatives - could take an approach of notifying listeners when the invocation to `play` or `stop` is received at the native layer for instance, rather than as a reaction to the actual playing state changing on the underlying player.

I don't think you and I are in any common servers on Discord, but feel free to reach out via Jochum if needed.

**Pull request merged**
